plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - ruby
    exclude_paths:
      - "app/controllers/"
      - "app/dashboards/"
      - "app/models/ability.rb"
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
    - "app/**"
    - "lib/**"
exclude_paths:
  - "config/"
  - "db/"
  - "public/"
  - "spec/"
  - "vendor/"
  - ".chglog/"
