queue_rules:
  - name: default
    merge_method: squash
    merge_conditions:
      - check-success = lint
      - check-success = scan_ruby
      - check-success = test
      - check-success = DCO
    autoqueue: true
pull_request_rules:
  - name: Queue maintainer PRs with lgtm label
    conditions:
      - base = main
      - author=@maintainers
      - label = lgtm
      - label != do-not-merge
    actions:
      queue:
        name: default
  - name: Auto-approve and queue dependabot PRs
    conditions:
      - base = main
      - author = dependabot[bot]
      - label != do-not-merge
      - -files~=\.github/workflows/
    actions:
      review:
        type: APPROVE
        message: Automatically approved by Mergify
      queue:
        name: default
  - name: Queue external PRs when approved by maintainer
    conditions:
      - base = main
      - -author=@maintainers
      - author != dependabot[bot]
      - approved-reviews-by=@maintainers
      - label != do-not-merge
    actions:
      queue:
        name: default
  - name: Keep PRs up to date with main
    conditions:
      - base = main
      - -conflict
      - -draft
      - -author = dependabot[bot]
      - label != do-not-merge
    actions:
      update: {}
merge_protections:
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = main
      - author != dependabot[bot]
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\
        \\))?:"
  - name: CI must pass
    description: All CI checks must pass. This protection prevents manual merges
      that bypass the merge queue.
    if:
      - base = main
    success_conditions:
      - check-success = lint
      - check-success = scan_ruby
      - check-success = test
      - check-success = DCO
  - name: Do not merge outdated PRs
    description: Make sure PRs are within 10 commits of the base branch before merging
    if:
      - base = main
    success_conditions:
      - "#commits-behind <= 10"
