inherit_gem:
  rubocop-rails-omakase: rubocop.yml
  rswag-specs: .rubocop_rspec_alias_config.yml

# Customizations
require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-thread_safety
  - rubocop-ordered_methods
AllCops:
  SuggestExtensions: true
  NewCops: enable
  TargetRubyVersion: 3.2
  ExtraDetails: true
#  DisabledByDefault: false

# Bundler
Bundler/OrderedGems:
  Enabled: true
Bundler/GemComment:
  Enabled: true
  OnlyFor: [ 'github', 'restrictive_version_specifiers', 'source', 'gist', 'git' ]
Bundler/InsecureProtocolSource:
  Enabled: true

# FactoryBot
FactoryBot:
  Enabled: true

# Layout
Layout/ClassStructure:
  Enabled: true
  Categories:
    association:
      - has_many
      - has_one
    attribute_macros:
      - attr_accessor
      - attr_reader
      - attr_writer
    macros:
      - validates
      - validate
    module_inclusion:
      - include
      - prepend
      - extend

# Lint
Lint/SymbolConversion:
  Enabled: true

# Metrics Cops
Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Max: 100
  Enabled: true
Metrics/ModuleLength:
  Description: 'Avoid modules longer than 100 lines of code.'
  Max: 100
  Enabled: true
Metrics/ParameterLists:
  Description: 'Pass no more than four parameters into a method.'
  Max: 4
  Enabled: true

# Naming
Naming/BlockForwarding:
  Enabled: true

# Ordered Methods
Layout/OrderedMethods:
  EnforcedStyle: alphabetical
  IgnoredMethods:
    - initialize
    - index
    - show
    - new
    - edit
    - create
    - update
    - destroy

# Rails
Rails:
  Enabled: true
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/I18nLocaleTexts: # At some point, we should enable this cop
  Enabled: false

# RSpec
RSpec:
  Enabled: true
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false # This cop causes issues with RSwag
RSpec/ExampleLength:
  Max: 20
  Enabled: true
RSpec/MultipleExpectations:
  Max: 5 # The default is 1, but we're a bit more lenient due to the nature of RSwag requests
  Enabled: true

# Security
Security/IoMethods:
  Enabled: true

# Performance
Performance/AncestorsInclude:
  Enabled: true
Performance/ArraySemiInfiniteRangeSlice:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/CaseWhenSplat:
  Enabled: true
Performance/CollectionLiteralInLoop:
  Enabled: true
  MinSize: 3
Performance/IoReadlines:
  Enabled: true
