services:
  web:
    image: ghcr.io/unclesp1d3r/cipherswarm:latest
    ports:
      - "80:80"
    environment:
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
      - REDIS_URL=redis://redis-db:6379
      - DATABASE_URL=postgres://root:password@postgres-db/
      - DB_HOST=postgres
      - MINIO_ENDPOINT=http://127.0.0.1:9000
    depends_on:
      redis-db:
        condition: service_started
      postgres-db:
        condition: service_healthy
      minio:
        condition: service_started
      sidekiq:
        condition: service_started
    volumes:
      - storage:/rails/storage
    networks:
      - minio
      - redis
      - postgres
      - web
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 5s
      retries: 30
    networks:
      - postgres
  minio:
    image: bitnami/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio:/bitnami/minio/data'
    networks:
      - minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=application

  redis-db:
    image: redis
    networks:
      - redis

  sidekiq:
    image: ghcr.io/unclesp1d3r/cipherswarm:latest
    command: bundle exec sidekiq
    environment:
      - RAILS_MASTER_KEY=$RAILS_MASTER_KEY
      - REDIS_URL=redis://redis-db:6379
      - DATABASE_URL=postgres://root:password@postgres-db/
      - DB_HOST=postgres
      - MINIO_ENDPOINT=http://minio:9000
    depends_on:
      redis-db:
        condition: service_started
      postgres-db:
        condition: service_healthy
      minio:
        condition: service_started
    volumes:
      - storage:/rails/storage
    networks:
      - minio
      - redis
      - postgres
networks:
  minio:
    driver: bridge
  redis:
  postgres:
  web:
    driver: bridge

volumes:
  storage:
  postgres:
  minio:
    driver: local
