require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/campaigns", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Campaign. As you add validations to Campaign, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Campaign.create! valid_attributes
      get campaigns_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      campaign = Campaign.create! valid_attributes
      get campaign_url(campaign)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_campaign_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      campaign = Campaign.create! valid_attributes
      get edit_campaign_url(campaign)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Campaign" do
        expect {
          post campaigns_url, params: { campaign: valid_attributes }
        }.to change(Campaign, :count).by(1)
      end

      it "redirects to the created campaign" do
        post campaigns_url, params: { campaign: valid_attributes }
        expect(response).to redirect_to(campaign_url(Campaign.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Campaign" do
        expect {
          post campaigns_url, params: { campaign: invalid_attributes }
        }.to change(Campaign, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post campaigns_url, params: { campaign: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested campaign" do
        campaign = Campaign.create! valid_attributes
        patch campaign_url(campaign), params: { campaign: new_attributes }
        campaign.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the campaign" do
        campaign = Campaign.create! valid_attributes
        patch campaign_url(campaign), params: { campaign: new_attributes }
        campaign.reload
        expect(response).to redirect_to(campaign_url(campaign))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        campaign = Campaign.create! valid_attributes
        patch campaign_url(campaign), params: { campaign: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested campaign" do
      campaign = Campaign.create! valid_attributes
      expect {
        delete campaign_url(campaign)
      }.to change(Campaign, :count).by(-1)
    end

    it "redirects to the campaigns list" do
      campaign = Campaign.create! valid_attributes
      delete campaign_url(campaign)
      expect(response).to redirect_to(campaigns_url)
    end
  end
end
