require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cracker_binaries", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # CrackerBinary. As you add validations to CrackerBinary, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CrackerBinary.create! valid_attributes
      get cracker_binaries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cracker_binary = CrackerBinary.create! valid_attributes
      get cracker_binary_url(cracker_binary)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cracker_binary_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cracker_binary = CrackerBinary.create! valid_attributes
      get edit_cracker_binary_url(cracker_binary)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CrackerBinary" do
        expect {
          post cracker_binaries_url, params: { cracker_binary: valid_attributes }
        }.to change(CrackerBinary, :count).by(1)
      end

      it "redirects to the created cracker_binary" do
        post cracker_binaries_url, params: { cracker_binary: valid_attributes }
        expect(response).to redirect_to(cracker_binary_url(CrackerBinary.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CrackerBinary" do
        expect {
          post cracker_binaries_url, params: { cracker_binary: invalid_attributes }
        }.to change(CrackerBinary, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post cracker_binaries_url, params: { cracker_binary: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cracker_binary" do
        cracker_binary = CrackerBinary.create! valid_attributes
        patch cracker_binary_url(cracker_binary), params: { cracker_binary: new_attributes }
        cracker_binary.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cracker_binary" do
        cracker_binary = CrackerBinary.create! valid_attributes
        patch cracker_binary_url(cracker_binary), params: { cracker_binary: new_attributes }
        cracker_binary.reload
        expect(response).to redirect_to(cracker_binary_url(cracker_binary))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        cracker_binary = CrackerBinary.create! valid_attributes
        patch cracker_binary_url(cracker_binary), params: { cracker_binary: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cracker_binary" do
      cracker_binary = CrackerBinary.create! valid_attributes
      expect {
        delete cracker_binary_url(cracker_binary)
      }.to change(CrackerBinary, :count).by(-1)
    end

    it "redirects to the cracker_binaries list" do
      cracker_binary = CrackerBinary.create! valid_attributes
      delete cracker_binary_url(cracker_binary)
      expect(response).to redirect_to(cracker_binaries_url)
    end
  end
end
