require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/word_lists", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # WordList. As you add validations to WordList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WordList.create! valid_attributes
      get word_lists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      word_list = WordList.create! valid_attributes
      get word_list_url(word_list)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_word_list_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      word_list = WordList.create! valid_attributes
      get edit_word_list_url(word_list)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WordList" do
        expect {
          post word_lists_url, params: { word_list: valid_attributes }
        }.to change(WordList, :count).by(1)
      end

      it "redirects to the created word_list" do
        post word_lists_url, params: { word_list: valid_attributes }
        expect(response).to redirect_to(word_list_url(WordList.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WordList" do
        expect {
          post word_lists_url, params: { word_list: invalid_attributes }
        }.to change(WordList, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post word_lists_url, params: { word_list: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested word_list" do
        word_list = WordList.create! valid_attributes
        patch word_list_url(word_list), params: { word_list: new_attributes }
        word_list.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the word_list" do
        word_list = WordList.create! valid_attributes
        patch word_list_url(word_list), params: { word_list: new_attributes }
        word_list.reload
        expect(response).to redirect_to(word_list_url(word_list))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        word_list = WordList.create! valid_attributes
        patch word_list_url(word_list), params: { word_list: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested word_list" do
      word_list = WordList.create! valid_attributes
      expect {
        delete word_list_url(word_list)
      }.to change(WordList, :count).by(-1)
    end

    it "redirects to the word_lists list" do
      word_list = WordList.create! valid_attributes
      delete word_list_url(word_list)
      expect(response).to redirect_to(word_lists_url)
    end
  end
end
