"""Remove duplicate timestamp fields from Resource model

Revision ID: 95f94e7b3e1c
Revises: 1587d62b626a
Create Date: 2025-08-19 02:49:05.798477+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95f94e7b3e1c"
down_revision: Union[str, None] = "1587d62b626a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
