# frozen_string_literal: true

# SPDX-FileCopyrightText:  2024 UncleSp1d3r
# SPDX-License-Identifier: MPL-2.0

# Base page object for attack resource forms (word lists, rule lists, mask lists)
# Provides common form interaction methods
class AttackResourceFormPage < BasePage
  # Fill in the name field
  # @param name [String] the resource name
  def fill_name(name)
    fill_in "Name", with: name
    self
  end

  # Fill in the description field
  # @param description [String] the resource description
  def fill_description(description)
    fill_in "Description", with: description
    self
  end

  # Attach a file to the form
  # @param file_path [String] the path to the file to attach
  def attach_file(file_path)
    session.attach_file("File", file_path)
    self
  end

  # Select projects by checking checkboxes
  # @param project_names [Array<String>] array of project names to select
  def select_projects(project_names)
    project_names.each do |name|
      check name
    end
    self
  end

  # Unselect projects by unchecking checkboxes
  # @param project_names [Array<String>] array of project names to unselect
  def unselect_projects(project_names)
    project_names.each do |name|
      uncheck name
    end
    self
  end

  # Check if project checkboxes are displayed (not radio buttons)
  # @return [Boolean] true if checkboxes are present
  def has_project_checkboxes?
    # Check for checkboxes generated by SimpleForm's :check_boxes association helper
    # (form uses: f.association :projects, as: :check_boxes)
    session.has_css?("input[type='checkbox'][name*='project_ids']")
  end

  # Check if project radio buttons are displayed
  # @return [Boolean] true if radio buttons are present (should always be false)
  def has_project_radio_buttons?
    session.has_css?("input[type='radio'][name*='project_ids']")
  end

  # Get all project checkbox labels
  # @return [Array<String>] array of project names available for selection
  def available_projects
    session.all("input[type='checkbox'][name*='project_ids']").map do |checkbox|
      # Find the associated label element using the checkbox's ID attribute
      # Note: Label structure depends on SimpleForm configuration
      checkbox_id = checkbox[:id]
      label = session.find("label[for='#{checkbox_id}']", visible: :all)
      label.text.strip
    end
  end

  # Submit the form
  def submit_form
    submit_primary_form
  end

  # Wait for direct upload to complete
  def wait_for_upload_complete
    session.has_no_css?(".direct-upload--pending", wait: 10)
    self
  end

  # Check for validation error messages
  # @param message [String] the error message to check for
  # @return [Boolean] true if the error message is displayed
  def has_validation_error?(message)
    has_content?(message)
  end
end
