services:
  app:
    user: vscode
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.2.2
        USER_UID: 1000
        USER_GID: 1000
        NODE_VERSION: lts/*
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - default
    links:
      - selenium
      - redis
      - postgres
    # ports:
    #   - 45678:45678
    depends_on:
      - selenium
      - redis
      - postgres
  selenium:
    image: seleniarm/standalone-chromium
    restart: unless-stopped
    networks:
      - default
  postgres:
    image: postgres:16.1
    restart: unless-stopped
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:7.2
    restart: unless-stopped
    networks:
      - default
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data:
