# frozen_string_literal: true

# SPDX-FileCopyrightText:  2024 UncleSp1d3r
# SPDX-License-Identifier: MPL-2.0

# ApplicationHelper is a collection of utility methods commonly used across the application views.
# It includes helper methods for generating CSS classes, managing content blocks,
# deriving site and page titles, generating URLs, sanitizing content, and other view-related functionalities.
module ApplicationHelper
  # Pagy 8 may not define Pagy::Frontend the same way as previous versions; guard the include.
  include Pagy::Frontend if defined?(Pagy::Frontend)

  # Returns the CSS class for the body element based on the current controller and action.
  # The CSS class is generated by combining the controller and action names, separated by hyphens.
  # If the controller name contains a slash ("/"), it is split and only the first part is used.
  # If the action name is present, it is appended to the controller name.
  # If the "page" parameter is present, it is appended to the controller and action names.
  #
  # @param params [Hash] The parameters hash containing the current controller, action, and page.
  # @return [String] The CSS class for the body element.
  def body_class(params)
    return unless params[:controller] && params[:action]

    controller = params[:controller].split("/").first
    action = params[:action]
    page = params[:page]

    classes = ["#{controller}", "#{controller}-#{action}"]
    classes << "#{controller}-#{action}-#{page}" if page

    classes.join(" ")
  end

  # Returns the content for the given name if it exists, otherwise returns the default value.
  #
  # @param name [Symbol] The name of the content block.
  # @param default [String] The default value to return if the content block does not exist.
  # @return [String] The content for the given name if it exists, otherwise the default value.
  def content_for_or(name, default = "")
    raise ArgumentError, "default must be a String" unless default.is_a?(String)

    if content_for?(name)
      content_for(name)
    else
      default
    end
  end

  # Returns the name of the current site.
  #
  # The current site name is derived from the name of the parent module of the Rails application,
  # converted to a human-readable format with capitalized words.
  #
  # Example:
  #   current_site #=> "Cipher Swarm"
  #
  # Returns a string representing the current site name.
  def current_site
    Rails.application.class.module_parent_name
         .underscore
         .humanize
         .split
         .map(&:capitalize)
         .join(" ")
  end

  # Returns the current title for the page.
  # The title is determined based on the current site, the content_for(:title) if present,
  # or the last part of the params[:controller] titleized.
  # Returns a string with the current title.
  def current_title(params)
    title = []
    title << current_site
    title << if content_for?(:title)
      content_for(:title)
    else
      params[:controller].split("/").last.titleize
    end
    title.uniq.join(" | ")
  end

  # Returns the current URL of the request.
  #
  # @return [String] The current URL.
  def current_url(request)
    "#{request.protocol}#{request.host_with_port}#{request.fullpath}"
  end

  # Sets the description for the current page.
  #
  # @param description [String] The description to be set.
  # @return [void]
  def description(description = "")
    content_for :description, description
  end

  # Safely checks authorization, returning false if no user context is available.
  #
  # This helper wraps the CanCanCan `can?` method to handle cases where authorization
  # checks are made outside of a request context (e.g., in Turbo Stream broadcasts
  # from model callbacks). When Warden is not available, it defaults to denying access.
  #
  # @param action [Symbol] The action to check (e.g., :read, :edit, :destroy)
  # @param subject [Object] The subject to check authorization against
  # @return [Boolean] True if authorized, false if not authorized or no user context
  def safe_can?(action, subject)
    can?(action, subject)
  rescue Warden::NotAuthenticated, NoMethodError => e
    # NoMethodError can occur when current_user is called without Warden
    # Warden::NotAuthenticated when Warden proxy is missing
    Rails.logger.debug { "[SafeAuthorization] Authorization check skipped - no user context: #{e.message}" }
    false
  end

  # Returns the Bootstrap badge class for a HashcatStatus status.
  #
  # @param status [String] The hashcat status string.
  # @return [String] The Bootstrap badge class for the status.
  def status_badge_class(status)
    case status.to_s
    when "running"
      "text-bg-primary"
    when "completed", "cracked", "exhausted"
      "text-bg-success"
    when "paused"
      "text-bg-warning"
    when "failed", "aborted", "aborted_session_checkpoint", "aborted_runtime_limit", "aborted_finish", "error"
      "text-bg-danger"
    when "initializing", "autotuning", "self_testing", "autodetecting"
      "text-bg-info"
    when "pending", "bypassed", "quit"
      "text-bg-secondary"
    else
      "text-bg-secondary"
    end
  end

  # Returns the Bootstrap badge class for an AgentError severity level.
  #
  # @param error [AgentError] The agent error record.
  # @return [String] The Bootstrap badge class for the severity.
  def severity_badge_class_for(error)
    case error.severity
    when "info"
      "text-bg-info"
    when "warning"
      "text-bg-warning"
    when "minor"
      "text-bg-warning"
    when "major"
      "text-bg-danger"
    when "critical"
      "text-bg-danger"
    when "fatal"
      "text-bg-dark"
    else
      "text-bg-secondary"
    end
  end
end
