name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv --version

      - name: Install dependencies
        run: |
          uv pip install ruff

      - name: Check formatting
        run: |
          ruff format --check .

      - name: Run Ruff linter
        run: |
          ruff check .

      # Optional: Comment on PR with formatting issues
      - name: Comment on PR
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `❌ Code quality checks failed!

            Please run the following commands locally to fix the issues:
            \`\`\`bash
            # Fix formatting issues
            ruff format .

            # Fix auto-fixable linting issues
            ruff check --fix .
            \`\`\`

            Then commit and push the changes.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
